<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?= $this->headTitle('Publogger')->setSeparator(' :: ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('keywords', '')
	        ->appendName('description', '')
	        ->appendName('language', 'English')
	        ->appendName('author', 'Khaleb Great')
        ?>

	</head>
    <body>

		<?= $this->content ?>

        <?= $this->inlineScript() ?>
    </body>
</html>
