<?php

namespace Application\Entity\Repository;

/**
 * PostTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
