<?php

namespace Application\Entity\Repository;

/**
 * PostGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
