<?php

namespace Application\Entity\Repository;

/**
 * PostImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
